"""initial schema — all tables, indexes, constraints

Baseline revision. Creates the full schema from the declarative metadata so the
first migration is authoritative and stays in lock-step with the ORM models. Subsequent
schema changes should be autogenerated (`alembic revision --autogenerate`).

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-06
"""
from __future__ import annotations

from alembic import op

from src.database import models  # noqa: F401 — populate metadata
from src.database.base import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
